'use strict';

Object.defineProperty(exports, "__esModule", {
	value: true
});
var component = exports.component = function component(content) {
	var opts = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
	var mutation = opts.mutation,
	    pathArr = opts.pathArr,
	    project = opts.project,
	    obj = opts.obj;

	var contents = '';
	contents += '<template>\n';
	contents += '\t<div class="v-tpl-form g-pd-lr-24 g-pd-t-24" style="padding-bottom: 70px">\n';
	contents += '\t\t<!-- \u8868\u5355 -->\n';
	contents += '\t\t<div class="g-m-b-32">\n';
	contents += '\t\t\t<' + project + '-section-title title="\u8868\u5355\u6837\u5F0F" class="g-m-b-24" />\n';
	contents += '\t\t\t<!-- 96\u4F4D\u6240\u6709label\u4E2D\u6700\u5BBD\u7684\u957F\u5EA6 -->\n';
	contents += '\t\t\t<vc-form \n';
	contents += '\t\t\t\tref="form" \n';
	contents += '\t\t\t\t:model="formValidate" \n';
	contents += '\t\t\t\t:rules="ruleValidate" \n';
	contents += '\t\t\t\t:label-width="96"\n';
	contents += '\t\t\t\tclass="g-pd-l-56 g-m-t-21"\n';
	contents += '\t\t\t\tposition="left"\n';
	contents += '\t\t\t\t@submit.native.prevent\n';
	contents += '\t\t\t>\n';
	contents += '\t\t\t\t<vc-form-item label="\u5546\u54C1\u540D\u79F0\uFF1A" prop="product_name">\n';
	contents += '\t\t\t\t\t<vc-input \n';
	contents += '\t\t\t\t\t\tv-model="formValidate.product_name"\n';
	contents += '\t\t\t\t\t\tclass="v-input" \n';
	contents += '\t\t\t\t\t\tplaceholder="\u8BF7\u8F93\u5165" \n';
	contents += '\t\t\t\t\t\tstyle="width: 300px"\n';
	contents += '\t\t\t\t\t/>\n';
	contents += '\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t<div class="g-flex g-m-b-26">\n';
	contents += '\t\t\t\t\t<div class="g-c-333 g-tr" style="width: 96px">\u5546\u54C1\u540D\u79F0\uFF1A</div>\n';
	contents += '\t\t\t\t\t<div class="g-c-999">\u5B89\u5FBD\u7701\u7535\u8BDD\u8D39</div>\n';
	contents += '\t\t\t\t</div>\n';
	contents += '\t\t\t\t<vc-form-item label="\u5546\u54C1\u4E3B\u56FE\uFF1A" prop="original_img" >\n';
	contents += '\t\t\t\t\t<vc-imgs-picker class="g-m-t-26" />\n';
	contents += '\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t<vc-form-item label="\u5546\u54C1\u8D27\u53F7\uFF1A" prop="product_sn">\n';
	contents += '\t\t\t\t\t<vc-input \n';
	contents += '\t\t\t\t\t\tv-model="formValidate.product_sn" \n';
	contents += '\t\t\t\t\t\tplaceholder="\u8BF7\u8F93\u5165"\n';
	contents += '\t\t\t\t\t\tstyle="width: 300px" \n';
	contents += '\t\t\t\t\t/>\n';
	contents += '\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t<vc-form-item label="\u5546\u54C1\u5B9E\u9645\u4EF7\u683C\uFF1A" prop="contact">\n';
	contents += '\t\t\t\t\t<vc-input \n';
	contents += '\t\t\t\t\t\tv-model="formValidate.contact" \n';
	contents += '\t\t\t\t\t\tplaceholder="\u8BF7\u586B\u5199\u5408\u540C\u7B7E\u8BA2\u516C\u53F8" \n';
	contents += '\t\t\t\t\t\tstyle="width: 300px"\n';
	contents += '\t\t\t\t\t/>\n';
	contents += '\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t<vc-form-item label="\u5546\u54C1\u5E02\u573A\u4EF7\u683C\uFF1A" prop="market_price">\n';
	contents += '\t\t\t\t\t<vc-input \n';
	contents += '\t\t\t\t\t\tv-model="formValidate.market_price" \n';
	contents += '\t\t\t\t\t\tplaceholder="\u8BF7\u586B\u5199\u5408\u540C\u7B7E\u8BA2\u516C\u53F8"\n';
	contents += '\t\t\t\t\t\tstyle="width: 300px"\n';
	contents += '\t\t\t\t\t/>\n';
	contents += '\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t<vc-form-item label="\u5546\u54C1\u91CD\u91CF\uFF1A" prop="weight">\n';
	contents += '\t\t\t\t\t<vc-input \n';
	contents += '\t\t\t\t\t\tv-model="formValidate.weight" \n';
	contents += '\t\t\t\t\t\tplaceholder="\u8BF7\u586B\u5199\u5408\u540C\u7B7E\u8BA2\u516C\u53F8"\n';
	contents += '\t\t\t\t\t\tstyle="width: 300px"\n';
	contents += '\t\t\t\t\t/>\n';
	contents += '\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t<vc-form-item label="\u5546\u54C1\u5206\u7C7B\uFF1A" prop="my_company">\n';
	contents += '\t\t\t\t\t<vc-select \n';
	contents += '\t\t\t\t\t\tv-model="formValidate.my_company"\n';
	contents += '\t\t\t\t\t\tclearable \n';
	contents += '\t\t\t\t\t\ttransfer\n';
	contents += '\t\t\t\t\t\tplaceholder="\u8BF7\u9009\u62E9\u6211\u65B9\u5408\u540C\u516C\u53F8"\n';
	contents += '\t\t\t\t\t\tstyle="width: 300px"\n';
	contents += '\t\t\t\t\t>\n';
	contents += '\t\t\t\t\t\t<vc-option \n';
	contents += '\t\t\t\t\t\t\tv-for="(item, index) in company" \n';
	contents += '\t\t\t\t\t\t\t:key="index" \n';
	contents += '\t\t\t\t\t\t\tvalue="item"\n';
	contents += '\t\t\t\t\t\t>\n';
	contents += '\t\t\t\t\t\t\t{{ item }}\n';
	contents += '\t\t\t\t\t\t</vc-option>\n';
	contents += '\t\t\t\t\t</vc-select>\n';
	contents += '\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t<vc-form-item label="\u5546\u54C1\u5C5E\u6027\u7EC4\uFF1A" prop="my_company">\n';
	contents += '\t\t\t\t\t<vc-select \n';
	contents += '\t\t\t\t\t\tv-model="formValidate.my_company"\n';
	contents += '\t\t\t\t\t\tclearable \n';
	contents += '\t\t\t\t\t\ttransfer\n';
	contents += '\t\t\t\t\t\tplaceholder="\u8BF7\u9009\u62E9\u6211\u65B9\u5408\u540C\u516C\u53F8"\n';
	contents += '\t\t\t\t\t\tstyle="width: 300px"\n';
	contents += '\t\t\t\t\t>\n';
	contents += '\t\t\t\t\t\t<vc-option \n';
	contents += '\t\t\t\t\t\t\tv-for="(item, index) in company" \n';
	contents += '\t\t\t\t\t\t\t:key="index" \n';
	contents += '\t\t\t\t\t\t\tvalue="item"\n';
	contents += '\t\t\t\t\t\t>\n';
	contents += '\t\t\t\t\t\t\t{{ item }}\n';
	contents += '\t\t\t\t\t\t</vc-option>\n';
	contents += '\t\t\t\t\t</vc-select>\n';
	contents += '\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t<vc-form-item \n';
	contents += '\t\t\t\t\tv-for="(item, index) in formValidate.items"\n';
	contents += '\t\t\t\t\t:key="item.index"\n';
	contents += '\t\t\t\t\t:label="index === 0 ? \'\u7F34\u6B3E\u65B9\u5F0F\uFF1A\' : \'\'"\n';
	contents += '\t\t\t\t>\n';
	contents += '\t\t\t\t\t<div class="g-form-block">\n';
	contents += '\t\t\t\t\t\t<vc-form-item\n';
	contents += '\t\t\t\t\t\t\t:prop="\'items.\' + index + \'.date\'" \n';
	contents += '\t\t\t\t\t\t\t:rules="{required: true, message: \'\u8BF7\u9009\u62E9\u6210\u4EA4\u65F6\u95F4\'}"\n';
	contents += '\t\t\t\t\t\t>\n';
	contents += '\t\t\t\t\t\t\t<vc-date-picker \n';
	contents += '\t\t\t\t\t\t\t\tv-model="item.date" \n';
	contents += '\t\t\t\t\t\t\t\tstyle="width: 300px"\n';
	contents += '\t\t\t\t\t\t\t\ttype="datetime"\n';
	contents += '\t\t\t\t\t\t\t\tplaceholder="\u8BF7\u9009\u62E9\u6210\u4EA4\u65F6\u95F4" \n';
	contents += '\t\t\t\t\t\t\t/>\n';
	contents += '\t\t\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t\t\t<vc-form-item \n';
	contents += '\t\t\t\t\t\t\t:prop="\'items.\' + index + \'.amount\'" \n';
	contents += '\t\t\t\t\t\t\t:rules="{required: true, message: \'\u8BF7\u8F93\u5165\u4ED8\u6B3E\u91D1\u989D\'}"\n';
	contents += '\t\t\t\t\t\t>\n';
	contents += '\t\t\t\t\t\t\t<vc-input-number\n';
	contents += '\t\t\t\t\t\t\t\tv-model="item.amount" \n';
	contents += '\t\t\t\t\t\t\t\t:min="0"\n';
	contents += '\t\t\t\t\t\t\t\t:precision="2"\n';
	contents += '\t\t\t\t\t\t\t\tstyle="width: 300px"\n';
	contents += '\t\t\t\t\t\t\t\tplaceholder="\u8BF7\u8F93\u5165\u4ED8\u6B3E\u91D1\u989D"\n';
	contents += '\t\t\t\t\t\t\t/>\n';
	contents += '\t\t\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t\t\t<vc-form-item\n';
	contents += '\t\t\t\t\t\t\t:prop="\'items.\' + index + \'.imgs\'" \n';
	contents += '\t\t\t\t\t\t\t:rules="{required: true, message: \'\u8BF7\u9009\u62E9\u56FE\u7247\'}"\n';
	contents += '\t\t\t\t\t\t\tstyle="margin-bottom: 0px !important"\n';
	contents += '\t\t\t\t\t\t>\n';
	contents += '\t\t\t\t\t\t\t<vc-imgs-picker \n';
	contents += '\t\t\t\t\t\t\t\tv-model="item.imgs" \n';
	contents += '\t\t\t\t\t\t\t\tstyle="width: 300px"\n';
	contents += '\t\t\t\t\t\t\t/>\n';
	contents += '\t\t\t\t\t\t\t<span\n';
	contents += '\t\t\t\t\t\t\t\tclass="g-m-t-5 g-inline-block" \n';
	contents += '\t\t\t\t\t\t\t\t@click="handleDel(item.index)"\n';
	contents += '\t\t\t\t\t\t\t>\n';
	contents += '\t\t\t\t\t\t\t\t\u5220\u9664\n';
	contents += '\t\t\t\t\t\t\t</span>\n';
	contents += '\t\t\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t\t</div>\n';
	contents += '\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t\t<vc-form-item label="">\n';
	contents += '\t\t\t\t\t<vc-button type="primary" @click="handleAdd">\n';
	contents += '\t\t\t\t\t\t+\u65B0\u5EFA\n';
	contents += '\t\t\t\t\t</vc-button>\n';
	contents += '\t\t\t\t</vc-form-item>\n';
	contents += '\t\t\t</vc-form>\n';
	contents += '\t\t</div>\n';
	contents += '\t\t<!-- \u5C55\u793A -->\n';
	contents += '\t\t<div class="g-m-b-32">\n';
	contents += '\t\t\t<' + project + '-section-title title="\u5F39\u6846\u5185\u4E0A\u4E0B\u8FB9\u8DDD16px" class="g-m-b-24" />\n';
	contents += '\t\t\t<!-- \u5C0F\u5F39\u6846\u5C45\u4E2D |  \u4E2D\u5F39\u6846\u8DDD\u79BB\u5DE6\u4FA7120 | \u5927\u5F39\u684624\uFF0C\u6709\u8FDB\u5EA6\u6761\u7684\u8DDD\u79BB\u5DE6\u4FA724-->\n';
	contents += '\t\t\t<div class="g-pd-l-56">\n';
	contents += '\t\t\t\t<div class="g-flex g-m-b-16">\n';
	contents += '\t\t\t\t\t<div class="g-c-333">\u5546\u54C1\u540D\u79F0\uFF1A</div>\n';
	contents += '\t\t\t\t\t<div class="g-c-51">\u5B89\u5FBD\u7701\u7535\u8BDD\u8D39</div>\n';
	contents += '\t\t\t\t</div>\n';
	contents += '\t\t\t\t<div class="g-flex g-m-b-16">\n';
	contents += '\t\t\t\t\t<div class="g-c-333">\u5546\u54C1\u540D\u79F0\uFF1A</div>\n';
	contents += '\t\t\t\t\t<div class="g-c-51">\u5B89\u5FBD\u7701\u7535\u8BDD\u8D39</div>\n';
	contents += '\t\t\t\t</div>\n';
	contents += '\t\t\t\t<div class="g-flex g-m-b-16">\n';
	contents += '\t\t\t\t\t<div class="g-c-333">\u5546\u54C1\u540D\u79F0\uFF1A</div>\n';
	contents += '\t\t\t\t\t<div class="g-c-51">\u5B89\u5FBD\u7701\u7535\u8BDD\u8D39</div>\n';
	contents += '\t\t\t\t</div>\n';
	contents += '\t\t\t\t<div class="g-flex g-m-b-16">\n';
	contents += '\t\t\t\t\t<div class="g-c-333">\u5546\u54C1\u540D\u79F0\uFF1A</div>\n';
	contents += '\t\t\t\t\t<div class="g-c-51">\u5B89\u5FBD\u7701\u7535\u8BDD\u8D39</div>\n';
	contents += '\t\t\t\t</div>\n';
	contents += '\t\t\t\t<div class="g-flex g-m-b-16">\n';
	contents += '\t\t\t\t\t<div class="g-c-333">\u5546\u54C1\u540D\u79F0\uFF1A</div>\n';
	contents += '\t\t\t\t\t<div class="g-c-51">\u5B89\u5FBD\u7701\u7535\u8BDD\u8D39</div>\n';
	contents += '\t\t\t\t</div>\n';
	contents += '\t\t\t</div>\n';
	contents += '\t\t</div>\n';
	contents += '\t\t<' + project + '-footer \n';
	contents += '\t\t\t@cancel="$router.back()"\n';
	contents += '\t\t\t@ok="handleSubmit" \n';
	contents += '\t\t/>\n';
	contents += '\t</div>\n';
	contents += '</template>\n';
	contents += '\n';
	contents += '<script>\n';
	contents += 'import SectionTitle from \'@components/_common/section-title/section-title\';\n';
	contents += 'import Footer from \'@components/_common/footer/footer\';\n';
	contents += '\n';
	contents += 'export default {\n';
	contents += '\tname: \'v-tpl-form\',\n';
	contents += '\tcomponents: {\n';
	contents += '\t\t\'' + project + '-section-title\': SectionTitle,\n';
	contents += '\t\t\'' + project + '-footer\': Footer,\n';
	contents += '\t},\n';
	contents += '\tdata() {\n';
	contents += '\t\treturn {\n';
	contents += '\t\t\tcompany: [\'\u963F\u91CC\', \'\u6709\u8D5E\', \'\u7F51\u6613\', \'\u6EF4\u6EF4\'],\n';
	contents += '\t\t\tindex: 1,\n';
	contents += '\t\t\tsetShow: false,\n';
	contents += '\t\t\tformValidate: {\n';
	contents += '\t\t\t\tproduct_name: \'xxxxx\',\n';
	contents += '\t\t\t\tproduct_sn: \'\',\n';
	contents += '\t\t\t\toriginal_img: \'\',\n';
	contents += '\t\t\t\tweight: \'\',\n';
	contents += '\t\t\t\titems: [\n';
	contents += '\t\t\t\t\t{\n';
	contents += '\t\t\t\t\t\tindex: 1,\n';
	contents += '\t\t\t\t\t\tdate: \'\',\n';
	contents += '\t\t\t\t\t\tpay_type: [],\n';
	contents += '\t\t\t\t\t\tamount: null,\n';
	contents += '\t\t\t\t\t\timgs: []\n';
	contents += '\t\t\t\t\t}\n';
	contents += '\t\t\t\t]\n';
	contents += '\t\t\t},\n';
	contents += '\t\t\truleValidate: {\n';
	contents += '\t\t\t\tproduct_name: [\n';
	contents += '\t\t\t\t\t{ \n';
	contents += '\t\t\t\t\t\trequired: true, \n';
	contents += '\t\t\t\t\t\tmessage: \'\u5546\u54C1\u540D\u79F0\u5FC5\u987B\u586B\u5199\uFF0C\u6700\u591A100\u4E2A\u5B57\' \n';
	contents += '\t\t\t\t\t}\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\tproduct_sn: [\n';
	contents += '\t\t\t\t\t{ \n';
	contents += '\t\t\t\t\t\trequired: true,\n';
	contents += '\t\t\t\t\t\tmessage: \'\u5546\u54C1\u8D27\u53F7\u5FC5\u987B\u586B\u5199\uFF0C\u4E14\u4E0D\u80FD\u8D85\u8FC764\u4E2A\u5B57\u7B26\' \n';
	contents += '\t\t\t\t\t}\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\toriginal_img: [\n';
	contents += '\t\t\t\t\t{ \n';
	contents += '\t\t\t\t\t\trequired: true, \n';
	contents += '\t\t\t\t\t\tmessage: \'\u6700\u5C11\u6DFB\u52A0\u4E00\u5F20\u5546\u54C1\u56FE\u7247\' \n';
	contents += '\t\t\t\t\t}\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\tcontact: [\n';
	contents += '\t\t\t\t\t{ \n';
	contents += '\t\t\t\t\t\trequired: true, \n';
	contents += '\t\t\t\t\t\tmessage: \'\u5546\u54C1\u4EF7\u683C\u4E3A\u4E0D\u80FD\u8D85\u8FC77\u4E2A\u5B57\u7B26\u7684\u6B63\u6570\uFF0C\u4E14\u4E0D\u80FD\u8D85\u8FC7\u5C0F\u6570\u70B9\u540E\u4E24\u4F4D\' \n';
	contents += '\t\t\t\t\t}\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\tweight: [\n';
	contents += '\t\t\t\t\t{ \n';
	contents += '\t\t\t\t\t\trequired: true, \n';
	contents += '\t\t\t\t\t\tmessage: \'\u5546\u54C1\u91CD\u91CF\u4E3A\u4E0D\u80FD\u8D85\u8FC79\u4E2A\u5B57\u7B26\u7684\u6B63\u6574\u6570\', \n';
	contents += '\t\t\t\t\t\ttrigger: \'change\' \n';
	contents += '\t\t\t\t\t}\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\t\n';
	contents += '\t\t\t}\n';
	contents += '\t\t};\n';
	contents += '\t},\n';
	contents += '\tmethods: {\n';
	contents += '\t\thandleAdd() {\n';
	contents += '\t\t\tthis.index++;\n';
	contents += '\t\t\tthis.formValidate.items.push({\n';
	contents += '\t\t\t\tindex: this.index,\n';
	contents += '\t\t\t\tdate: \'\',\n';
	contents += '\t\t\t\tpay_type: [],\n';
	contents += '\t\t\t\tamount: null\n';
	contents += '\t\t\t});\n';
	contents += '\t\t},\n';
	contents += '\t\thandleDel(index) {\n';
	contents += '\t\t\tthis.formValidate.items = this.formValidate.items.filter((item) => {\n';
	contents += '\t\t\t\treturn item.index !== index;\n';
	contents += '\t\t\t});\n';
	contents += '\t\t},\n';
	contents += '\t\thandleSubmit(name) {\n';
	contents += '\t\t\tthis.$refs.form.validate((isValid) => {\n';
	contents += '\t\t\t\tif (isValid) {\n';
	contents += '\t\t\t\t\tMessage.success(\'Success!\');\n';
	contents += '\t\t\t\t} else {\n';
	contents += '\t\t\t\t\tMessage.error(\'Fail!\');\n';
	contents += '\t\t\t\t}\n';
	contents += '\t\t\t});\n';
	contents += '\t\t},\n';
	contents += '\t\thandleSet() {\n';
	contents += '\t\t\tthis.setShow = !this.setShow;\n';
	contents += '\t\t\treturn this.setShow;\n';
	contents += '\t\t},\n';
	contents += '\t},\n';
	contents += '};\n';
	contents += '</script>\n';
	contents += '\n';
	contents += '<style lang="scss">\n';
	contents += '</style>\n';

	return contents;
};