'use strict';

Object.defineProperty(exports, "__esModule", {
	value: true
});
var component = exports.component = function component(content) {
	var opts = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
	var mutation = opts.mutation,
	    pathArr = opts.pathArr,
	    project = opts.project,
	    obj = opts.obj;

	var contents = '';
	contents += '<template>\n';
	contents += '\t<i-form \n';
	contents += '\t\tref="form" \n';
	contents += '\t\t:model="formValidate" \n';
	contents += '\t\t:rules="ruleValidate" \n';
	contents += '\t\t:label-width="120"\n';
	contents += '\t\tclass="v-tpl-form"\n';
	contents += '\t\tstyle="width: 500px" \n';
	contents += '\t\tposition="left"\n';
	contents += '\t>\n';
	contents += '\t\t<i-form-item label="\u5BA2\u6237\u516C\u53F8\u540D\u79F0:" prop="name">\n';
	contents += '\t\t\t<i-input v-model="formValidate.name" disabled placeholder="\u8BF7\u8F93\u5165\u5BA2\u6237\u516C\u53F8\u540D\u79F0" />\n';
	contents += '\t\t</i-form-item>\n';
	contents += '\t\t<i-form-item label="\u5BA2\u6237\u59D3\u540D:" prop="customer_name">\n';
	contents += '\t\t\t<i-input v-model="formValidate.customer_name" placeholder="\u8BF7\u8F93\u5165\u5BA2\u6237\u59D3\u540D" />\n';
	contents += '\t\t</i-form-item>\n';
	contents += '\t\t<i-form-item label="\u5BA2\u6237\u5408\u540C\u516C\u53F8:" prop="contact">\n';
	contents += '\t\t\t<i-input v-model="formValidate.contact" placeholder="\u8BF7\u586B\u5199\u5408\u540C\u7B7E\u8BA2\u516C\u53F8" />\n';
	contents += '\t\t</i-form-item>\n';
	contents += '\t\t<i-form-item label="\u6211\u65B9\u5408\u540C\u516C\u53F8:" prop="my_company">\n';
	contents += '\t\t\t<i-select \n';
	contents += '\t\t\t\tv-model="formValidate.my_company"\n';
	contents += '\t\t\t\tclearable \n';
	contents += '\t\t\t\tplaceholder="\u8BF7\u9009\u62E9\u6211\u65B9\u5408\u540C\u516C\u53F8"\n';
	contents += '\t\t\t>\n';
	contents += '\t\t\t\t<i-option \n';
	contents += '\t\t\t\t\tv-for="(item, index) in company" \n';
	contents += '\t\t\t\t\t:key="index" \n';
	contents += '\t\t\t\t\tvalue="item"\n';
	contents += '\t\t\t\t>\n';
	contents += '\t\t\t\t\t{{ item }}\n';
	contents += '\t\t\t\t</i-option>\n';
	contents += '\t\t\t</i-select>\n';
	contents += '\t\t\t<span class="_right">\u6DFB\u52A0</span>\n';
	contents += '\t\t</i-form-item>\n';
	contents += '\t\t<i-form-item label="\u6210\u4EA4\u65F6\u95F4" prop="deal_time">\n';
	contents += '\t\t\t<i-date-picker \n';
	contents += '\t\t\t\tv-model="formValidate.deal_time" \n';
	contents += '\t\t\t\tstyle="width: 100%"\n';
	contents += '\t\t\t\ttype="datetime" \n';
	contents += '\t\t\t\tplaceholder="\u8BF7\u9009\u62E9\u6210\u4EA4\u65F6\u95F4"\n';
	contents += '\t\t\t/>\n';
	contents += '\t\t</i-form-item>\n';
	contents += '\t\t<i-form-item label="\u5BA2\u6237\u624B\u673A\u53F7" prop="mobile">\n';
	contents += '\t\t\t<i-input \n';
	contents += '\t\t\t\tv-model="formValidate.mobile" \n';
	contents += '\t\t\t\t:maxlength="11"\n';
	contents += '\t\t\t\tplaceholder="\u8BF7\u8F93\u5165\u5BA2\u6237\u624B\u673A\u53F7"\n';
	contents += '\t\t\t/>\n';
	contents += '\t\t</i-form-item>\n';
	contents += '\t\t<i-form-item label="\u4E0D\u5206\u5355\u8BA4\u8BC1" prop="permit">\n';
	contents += '\t\t\t<i-input \n';
	contents += '\t\t\t\tv-model="formValidate.permit" \n';
	contents += '\t\t\t\tplaceholder="\u8BF7\u8F93\u5165\u8BA4\u8BC1\u9A8C\u8BC1\u7801"\n';
	contents += '\t\t\t/>\n';
	contents += '\t\t</i-form-item>\n';
	contents += '\t\t<i-form-item label="\u5408\u540C\u91D1\u989D" prop="amount">\n';
	contents += '\t\t\t<i-input-number\n';
	contents += '\t\t\t\tv-model="formValidate.amount" \n';
	contents += '\t\t\t\t:min="0"\n';
	contents += '\t\t\t\t:precision="2"\n';
	contents += '\t\t\t\tstyle="width: 100%"\n';
	contents += '\t\t\t\tplaceholder="\u8BF7\u8F93\u5165\u5408\u540C\u91D1\u989D"\n';
	contents += '\t\t\t/>\n';
	contents += '\t\t</i-form-item>\n';
	contents += '\t\t<i-form-item \n';
	contents += '\t\t\tv-for="(item, index) in formValidate.items"\n';
	contents += '\t\t\t:key="item.index"\n';
	contents += '\t\t\t\n';
	contents += '\t\t\t:label="index === 0 ? \'\u7F34\u6B3E\u65B9\u5F0F\' : \'\'"\n';
	contents += '\t\t>\n';
	contents += '\t\t\t<i-form-item\n';
	contents += '\t\t\t\t:prop="\'items.\' + index + \'.date\'" \n';
	contents += '\t\t\t\t:rules="{required: true, message: \'\u8BF7\u9009\u62E9\u6210\u4EA4\u65F6\u95F4\'}"\n';
	contents += '\t\t\t>\n';
	contents += '\t\t\t\t<i-date-picker \n';
	contents += '\t\t\t\t\tv-model="item.date" \n';
	contents += '\t\t\t\t\tstyle="width: 100%" \n';
	contents += '\t\t\t\t\ttype="datetime"\n';
	contents += '\t\t\t\t\tplaceholder="\u8BF7\u9009\u62E9\u6210\u4EA4\u65F6\u95F4" \n';
	contents += '\t\t\t\t/>\n';
	contents += '\t\t\t</i-form-item>\n';
	contents += '\t\t\t<i-form-item \n';
	contents += '\t\t\t\t:prop="\'items.\' + index + \'.pay_type\'" \n';
	contents += '\t\t\t\t:rules="{required: true, message: \'\u9009\u62E9\u4ED8\u6B3E\u65B9\u5F0F\'}"\n';
	contents += '\t\t\t>\n';
	contents += '\t\t\t\t<i-cascader \n';
	contents += '\t\t\t\t\t:data="payType" \n';
	contents += '\t\t\t\t\tv-model="item.pay_type" \n';
	contents += '\t\t\t\t\tclass="g-m-t-24"\n';
	contents += '\t\t\t\t\tplaceholder="\u9009\u62E9\u4ED8\u6B3E\u65B9\u5F0F"\n';
	contents += '\t\t\t\t/>\n';
	contents += '\t\t\t</i-form-item>\n';
	contents += '\t\t\t<i-form-item \n';
	contents += '\t\t\t\t:prop="\'items.\' + index + \'.amount\'" \n';
	contents += '\t\t\t\t:rules="{required: true, message: \'\u8BF7\u8F93\u5165\u4ED8\u6B3E\u91D1\u989D\'}"\n';
	contents += '\t\t\t>\n';
	contents += '\t\t\t\t<i-input-number\n';
	contents += '\t\t\t\t\tv-model="item.amount" \n';
	contents += '\t\t\t\t\t:min="0"\n';
	contents += '\t\t\t\t\t:precision="2"\n';
	contents += '\t\t\t\t\tstyle="width: 100%; margin-top: 20px"\n';
	contents += '\t\t\t\t\tplaceholder="\u8BF7\u8F93\u5165\u4ED8\u6B3E\u91D1\u989D"\n';
	contents += '\t\t\t\t/>\n';
	contents += '\t\t\t</i-form-item>\n';
	contents += '\t\t\t<i-form-item\n';
	contents += '\t\t\t\t:prop="\'items.\' + index + \'.imgs\'" \n';
	contents += '\t\t\t\t:rules="{required: true, message: \'\u8BF7\u9009\u62E9\u56FE\u7247\'}"\n';
	contents += '\t\t\t>\n';
	contents += '\t\t\t\t<vc-imgs-picker v-model="item.imgs" class="g-m-t-24" />\n';
	contents += '\t\t\t</i-form-item>\n';
	contents += '\t\t\t\n';
	contents += '\t\t\t<span\n';
	contents += '\t\t\t\tclass="_del" \n';
	contents += '\t\t\t\t@click="handleDel(item.index)"\n';
	contents += '\t\t\t>\n';
	contents += '\t\t\t\t\u5220\u9664\n';
	contents += '\t\t\t</span>\n';
	contents += '\t\t</i-form-item>\n';
	contents += '\t\t<div class="g-flex-ac">\n';
	contents += '\t\t\t<div style="width: 120px"/>\n';
	contents += '\t\t\t<div class="btn" @click="handleAdd">Add Item</div>\n';
	contents += '\t\t</div>\n';
	contents += '\t\t<div class="g-flex-ac">\n';
	contents += '\t\t\t<div style="width: 120px"/>\n';
	contents += '\t\t\t<div class="btn g-m-t-20" @click="handleSubmit">\u63D0\u4EA4</div>\n';
	contents += '\t\t</div>\n';
	contents += '\t</i-form>\n';
	contents += '</template>\n';
	contents += '\n';
	contents += '<script>\n';
	// contents += `import * as types from '@mutations/${mutation}';\n`;
	contents += 'import { \n';
	contents += '\tForm, FormItem, Input, InputNumber, \n';
	contents += '\tSelect, Option, DatePicker, Cascader, Message\n';
	contents += '} from \'iview\';\n';
	contents += '// utils\n';
	contents += 'import { dataValidity } from \'@utils/utils\';\n';
	contents += 'import { ImgsPicker } from \'wya-vc\';\n';
	contents += '\n';
	contents += 'const data = [\n';
	contents += '\t{\n';
	contents += '\t\tvalue: \'beijing\',\n';
	contents += '\t\tlabel: \'\u5317\u4EAC\',\n';
	contents += '\t\tchildren: [\n';
	contents += '\t\t\t{\n';
	contents += '\t\t\t\tvalue: \'gugong\',\n';
	contents += '\t\t\t\tlabel: \'\u6545\u5BAB\'\n';
	contents += '\t\t\t},\n';
	contents += '\t\t\t{\n';
	contents += '\t\t\t\tvalue: \'tiantan\',\n';
	contents += '\t\t\t\tlabel: \'\u5929\u575B\'\n';
	contents += '\t\t\t},\n';
	contents += '\t\t\t{\n';
	contents += '\t\t\t\tvalue: \'wangfujing\',\n';
	contents += '\t\t\t\tlabel: \'\u738B\u5E9C\u4E95\'\n';
	contents += '\t\t\t}\n';
	contents += '\t\t]\n';
	contents += '\t}, \n';
	contents += '\t{\n';
	contents += '\t\tvalue: \'jiangsu\',\n';
	contents += '\t\tlabel: \'\u6C5F\u82CF\',\n';
	contents += '\t\tchildren: [\n';
	contents += '\t\t\t{\n';
	contents += '\t\t\t\tvalue: \'nanjing\',\n';
	contents += '\t\t\t\tlabel: \'\u5357\u4EAC\',\n';
	contents += '\t\t\t\tchildren: [\n';
	contents += '\t\t\t\t\t{\n';
	contents += '\t\t\t\t\t\tvalue: \'fuzimiao\',\n';
	contents += '\t\t\t\t\t\tlabel: \'\u592B\u5B50\u5E99\',\n';
	contents += '\t\t\t\t\t}\n';
	contents += '\t\t\t\t]\n';
	contents += '\t\t\t},\n';
	contents += '\t\t\t{\n';
	contents += '\t\t\t\tvalue: \'suzhou\',\n';
	contents += '\t\t\t\tlabel: \'\u82CF\u5DDE\',\n';
	contents += '\t\t\t\tchildren: [\n';
	contents += '\t\t\t\t\t{\n';
	contents += '\t\t\t\t\t\tvalue: \'zhuozhengyuan\',\n';
	contents += '\t\t\t\t\t\tlabel: \'\u62D9\u653F\u56ED\',\n';
	contents += '\t\t\t\t\t},\n';
	contents += '\t\t\t\t\t{\n';
	contents += '\t\t\t\t\t\tvalue: \'shizilin\',\n';
	contents += '\t\t\t\t\t\tlabel: \'\u72EE\u5B50\u6797\',\n';
	contents += '\t\t\t\t\t}\n';
	contents += '\t\t\t\t]\n';
	contents += '\t\t\t}\n';
	contents += '\t\t],\n';
	contents += '\t}];\n';
	contents += '\n';
	contents += 'export default {\n';
	contents += '\tname: \'' + project + '-content\',\n';
	contents += '\tcomponents: {\n';
	contents += '\t\t\'i-form\': Form,\n';
	contents += '\t\t\'i-form-item\': FormItem,\n';
	contents += '\t\t\'i-input\': Input,\n';
	contents += '\t\t\'i-input-number\': InputNumber,\n';
	contents += '\t\t\'i-select\': Select,\n';
	contents += '\t\t\'i-option\': Option,\n';
	contents += '\t\t\'i-date-picker\': DatePicker,\n';
	contents += '\t\t\'i-cascader\': Cascader,\n';
	contents += '\t\t\'vc-imgs-picker\': ImgsPicker\n';
	contents += '\t},\n';
	contents += '\tdata() {\n';
	contents += '\t\treturn {\n';
	contents += '\t\t\tcompany: [\'\u963F\u91CC\', \'\u6709\u8D5E\', \'\u7F51\u6613\', \'\u6EF4\u6EF4\'],\n';
	contents += '\t\t\tpayType: data,\n';
	contents += '\t\t\tindex: 1,\n';
	contents += '\t\t\tformValidate: {\n';
	contents += '\t\t\t\tname: \'xxxxx\',\n';
	contents += '\t\t\t\tcustomer_name: \'\',\n';
	contents += '\t\t\t\tcontact: \'\',\n';
	contents += '\t\t\t\tmy_company: \'\',\n';
	contents += '\t\t\t\tdeal_time: \'\',\n';
	contents += '\t\t\t\tmobile: \'\',\n';
	contents += '\t\t\t\tpermit: \'\',\n';
	contents += '\t\t\t\tamount: null,\n';
	contents += '\t\t\t\titems: [\n';
	contents += '\t\t\t\t\t{\n';
	contents += '\t\t\t\t\t\tindex: 1,\n';
	contents += '\t\t\t\t\t\tdate: \'\',\n';
	contents += '\t\t\t\t\t\tpay_type: [],\n';
	contents += '\t\t\t\t\t\tamount: null,\n';
	contents += '\t\t\t\t\t\timgs: []\n';
	contents += '\t\t\t\t\t}\n';
	contents += '\t\t\t\t]\n';
	contents += '\t\t\t},\n';
	contents += '\t\t\truleValidate: {\n';
	contents += '\t\t\t\tname: [\n';
	contents += '\t\t\t\t\t{ required: true, message: \'\u8BF7\u8F93\u5165\u5BA2\u6237\u516C\u53F8\u540D\u79F0\' }\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\tcustomer_name: [\n';
	contents += '\t\t\t\t\t{ required: true, message: \'\u8BF7\u8F93\u5165\u5BA2\u6237\u59D3\u540D\' }\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\tcontact: [\n';
	contents += '\t\t\t\t\t{ required: true, message: \'\u8BF7\u586B\u5199\u5408\u540C\u7B7E\u8BA2\u516C\u53F8\' }\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\tmy_company: [\n';
	contents += '\t\t\t\t\t{ required: true, message: \'\u8BF7\u9009\u62E9\u6211\u65B9\u5408\u540C\u516C\u53F8\', trigger: \'change\' }\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\tdeal_time: [\n';
	contents += '\t\t\t\t\t{ required: true, type: "date", message: \'\u8BF7\u9009\u62E9\u6210\u4EA4\u65F6\u95F4\', trigger: \'change\' }\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\tmobile: [\n';
	contents += '\t\t\t\t\t{ required: true, message: \'\u8BF7\u8F93\u5165\u5BA2\u6237\u624B\u673A\u53F7\', trigger: \'blur\' }, \n';
	contents += '\t\t\t\t\t{ type: \'validMobile\', message: \'\u624B\u673A\u53F7\u683C\u5F0F\u4E0D\u6B63\u786E\', validator: dataValidity }\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\tpermit: [\n';
	contents += '\t\t\t\t\t{ required: true, message: \'\u8BF7\u8F93\u5165\u8BA4\u8BC1\u9A8C\u8BC1\u7801\' }\n';
	contents += '\t\t\t\t],\n';
	contents += '\t\t\t\tamount: [\n';
	contents += '\t\t\t\t\t{ required: true, type: \'number\', message: \'\u8BF7\u8F93\u5165\u5408\u540C\u91D1\u989D\' }\n';
	contents += '\t\t\t\t]\n';
	contents += '\t\t\t}\n';
	contents += '\t\t};\n';
	contents += '\t},\n';
	contents += '\tmounted() {\n';
	contents += '\t},\n';
	contents += '\tmethods: {\n';
	contents += '\t\thandleAdd() {\n';
	contents += '\t\t\tthis.index++;\n';
	contents += '\t\t\tthis.formValidate.items.push({\n';
	contents += '\t\t\t\tindex: this.index,\n';
	contents += '\t\t\t\tdate: \'\',\n';
	contents += '\t\t\t\tpay_type: [],\n';
	contents += '\t\t\t\tamount: null\n';
	contents += '\t\t\t});\n';
	contents += '\t\t},\n';
	contents += '\t\thandleDel(index) {\n';
	contents += '\t\t\tthis.formValidate.items = this.formValidate.items.filter((item) => {\n';
	contents += '\t\t\t\treturn item.index !== index;\n';
	contents += '\t\t\t});\n';
	contents += '\t\t},\n';
	contents += '\t\thandleSubmit(name) {\n';
	contents += '\t\t\tthis.$refs.form.validate((isValid) => {\n';
	contents += '\t\t\t\tif (isValid) {\n';
	contents += '\t\t\t\t\tMessage.success(\'Success!\');\n';
	contents += '\t\t\t\t} else {\n';
	contents += '\t\t\t\t\tMessage.error(\'Fail!\');\n';
	contents += '\t\t\t\t}\n';
	contents += '\t\t\t});\n';
	contents += '\t\t},\n';
	contents += '\t},\n';
	contents += '};\n';
	contents += '</script>\n';
	contents += '\n';
	contents += '<style lang="scss" scoped>\n';
	contents += '.v-tpl-form {\n';
	contents += '\t.btn {\n';
	contents += '\t\tcolor: #0085ff;\n';
	contents += '\t\tcursor: pointer;\n';
	contents += '\t}\n';
	contents += '\t._right {\n';
	contents += '\t\t@extend .btn;\n';
	contents += '\t\tposition: absolute; \n';
	contents += '\t\tright: -30px; \n';
	contents += '\t\ttop: 0;\n';
	contents += '\t}\n';
	contents += '\t._del {\n';
	contents += '\t\t@extend .btn;\n';
	contents += '\t\tdisplay: block;\n';
	contents += '\t\tmargin-top: 24px;\n';
	contents += '\t}\n';
	contents += '}\n';
	contents += '</style>\n';

	return contents;
};