export const component = (content, opts = {}) => {
	const { mutation, pathArr, project, obj, env } = opts;
	let m = env === 'mobile' ? 'm' : '';

	let contents = '';
	contents += `<template>\n`;
	contents += `	<div class="v-tpl-form g-pd-lr-24 g-pd-t-24" style="padding-bottom: 70px">\n`;
	contents += `		<!-- 表单 -->\n`;
	contents += `		<div class="g-m-b-32">\n`;
	contents += `			<h3 class="g-m-b-24">表单样式</h3>\n`;
	contents += `			<!-- 96位所有label中最宽的长度 -->\n`;
	contents += `			<vc${m}-form \n`;
	contents += `				ref="form" \n`;
	contents += `				:model="formValidate" \n`;
	contents += `				:rules="ruleValidate" \n`;
	contents += `				:label-width="96"\n`;
	contents += `				class="g-pd-l-56 g-m-t-21"\n`;
	contents += `				position="left"\n`;
	contents += `				@submit.native.prevent\n`;
	contents += `			>\n`;
	contents += `				<vc${m}-form-item label="商品名称：" prop="product_name">\n`;
	contents += `					<vc${m}-input \n`;
	contents += `						v-model="formValidate.product_name"\n`;
	contents += `						class="v-input" \n`;
	contents += `						placeholder="请输入" \n`;
	contents += `						style="width: 300px"\n`;
	contents += `					/>\n`;
	contents += `				</vc${m}-form-item>\n`;
	contents += `				<div class="g-flex g-m-b-26">\n`;
	contents += `					<div class="g-c-333 g-tr" style="width: 96px">商品名称：</div>\n`;
	contents += `					<div class="g-c-999">安徽省电话费</div>\n`;
	contents += `				</div>\n`;
	contents += `				<vc${m}-form-item label="商品主图：" prop="original_img" >\n`;
	contents += `					<vc${m}-imgs-picker class="g-m-t-26" />\n`;
	contents += `				</vc${m}-form-item>\n`;
	contents += `				<vc${m}-form-item label="商品货号：" prop="product_sn">\n`;
	contents += `					<vc${m}-input \n`;
	contents += `						v-model="formValidate.product_sn" \n`;
	contents += `						placeholder="请输入"\n`;
	contents += `						style="width: 300px" \n`;
	contents += `					/>\n`;
	contents += `				</vc${m}-form-item>\n`;
	contents += `				<vc${m}-form-item label="商品实际价格：" prop="contact">\n`;
	contents += `					<vc${m}-input \n`;
	contents += `						v-model="formValidate.contact" \n`;
	contents += `						placeholder="请填写合同签订公司" \n`;
	contents += `						style="width: 300px"\n`;
	contents += `					/>\n`;
	contents += `				</vc${m}-form-item>\n`;
	contents += `				<vc${m}-form-item label="商品市场价格：" prop="market_price">\n`;
	contents += `					<vc${m}-input \n`;
	contents += `						v-model="formValidate.market_price" \n`;
	contents += `						placeholder="请填写合同签订公司"\n`;
	contents += `						style="width: 300px"\n`;
	contents += `					/>\n`;
	contents += `				</vc${m}-form-item>\n`;
	contents += `				<vc${m}-form-item label="商品重量：" prop="weight">\n`;
	contents += `					<vc${m}-input \n`;
	contents += `						v-model="formValidate.weight" \n`;
	contents += `						placeholder="请填写合同签订公司"\n`;
	contents += `						style="width: 300px"\n`;
	contents += `					/>\n`;
	contents += `				</vc${m}-form-item>\n`;
	contents += `				<vc${m}-form-item label="商品分类：" prop="my_company">\n`;
	contents += `					<vc${m}-select \n`;
	contents += `						v-model="formValidate.my_company"\n`;
	contents += `						clearable \n`;
	contents += `						transfer\n`;
	contents += `						placeholder="请选择我方合同公司"\n`;
	contents += `						style="width: 300px"\n`;
	contents += `					>\n`;
	contents += `						<vc${m}-option \n`;
	contents += `							v-for="(item, index) in company" \n`;
	contents += `							:key="index" \n`;
	contents += `							value="item"\n`;
	contents += `						>\n`;
	contents += `							{{ item }}\n`;
	contents += `						</vc${m}-option>\n`;
	contents += `					</vc${m}-select>\n`;
	contents += `				</vc${m}-form-item>\n`;
	contents += `				<vc${m}-form-item label="商品属性组：" prop="my_company">\n`;
	contents += `					<vc${m}-select \n`;
	contents += `						v-model="formValidate.my_company"\n`;
	contents += `						clearable \n`;
	contents += `						transfer\n`;
	contents += `						placeholder="请选择我方合同公司"\n`;
	contents += `						style="width: 300px"\n`;
	contents += `					>\n`;
	contents += `						<vc${m}-option \n`;
	contents += `							v-for="(item, index) in company" \n`;
	contents += `							:key="index" \n`;
	contents += `							value="item"\n`;
	contents += `						>\n`;
	contents += `							{{ item }}\n`;
	contents += `						</vc${m}-option>\n`;
	contents += `					</vc${m}-select>\n`;
	contents += `				</vc${m}-form-item>\n`;
	contents += `				<vc${m}-form-item \n`;
	contents += `					v-for="(item, index) in formValidate.items"\n`;
	contents += `					:key="item.index"\n`;
	contents += `					:label="index === 0 ? '缴款方式：' : ''"\n`;
	contents += `				>\n`;
	contents += `					<div class="g-form-block">\n`;
	contents += `						<vc${m}-form-item\n`;
	contents += `							:prop="'items.' + index + '.date'" \n`;
	contents += `							:rules="{required: true, message: '请选择成交时间'}"\n`;
	contents += `						>\n`;
	contents += `							<vc${m}-date-picker \n`;
	contents += `								v-model="item.date" \n`;
	contents += `								style="width: 300px"\n`;
	contents += `								type="datetime"\n`;
	contents += `								placeholder="请选择成交时间" \n`;
	contents += `							/>\n`;
	contents += `						</vc${m}-form-item>\n`;
	contents += `						<vc${m}-form-item \n`;
	contents += `							:prop="'items.' + index + '.amount'" \n`;
	contents += `							:rules="{required: true, message: '请输入付款金额'}"\n`;
	contents += `						>\n`;
	contents += `							<vc${m}-input-number\n`;
	contents += `								v-model="item.amount" \n`;
	contents += `								:min="0"\n`;
	contents += `								:precision="2"\n`;
	contents += `								style="width: 300px"\n`;
	contents += `								placeholder="请输入付款金额"\n`;
	contents += `							/>\n`;
	contents += `						</vc${m}-form-item>\n`;
	contents += `						<vc${m}-form-item\n`;
	contents += `							:prop="'items.' + index + '.imgs'" \n`;
	contents += `							:rules="{required: true, message: '请选择图片'}"\n`;
	contents += `							style="margin-bottom: 0px !important"\n`;
	contents += `						>\n`;
	contents += `							<vc${m}-imgs-picker \n`;
	contents += `								v-model="item.imgs" \n`;
	contents += `								style="width: 300px"\n`;
	contents += `							/>\n`;
	contents += `							<span\n`;
	contents += `								class="g-m-t-5 g-inline-block" \n`;
	contents += `								@click="handleDel(item.index)"\n`;
	contents += `							>\n`;
	contents += `								删除\n`;
	contents += `							</span>\n`;
	contents += `						</vc${m}-form-item>\n`;
	contents += `					</div>\n`;
	contents += `				</vc${m}-form-item>\n`;
	contents += `				<vc${m}-form-item label="">\n`;
	contents += `					<vc${m}-button type="primary" @click="handleAdd">\n`;
	contents += `						+新建\n`;
	contents += `					</vc${m}-button>\n`;
	contents += `				</vc${m}-form-item>\n`;
	contents += `			</vc${m}-form>\n`;
	contents += `		</div>\n`;
	contents += `		<!-- 展示 -->\n`;
	contents += `		<div class="g-m-b-32">\n`;
	contents += `			<h3 class="g-m-b-24">弹框内上下边距16px</h3>\n`;
	contents += `			<!-- 小弹框居中 |  中弹框距离左侧120 | 大弹框24，有进度条的距离左侧24-->\n`;
	contents += `			<div class="g-pd-l-56">\n`;
	contents += `				<div class="g-flex g-m-b-16">\n`;
	contents += `					<div class="g-c-333">商品名称：</div>\n`;
	contents += `					<div class="g-c-51">安徽省电话费</div>\n`;
	contents += `				</div>\n`;
	contents += `				<div class="g-flex g-m-b-16">\n`;
	contents += `					<div class="g-c-333">商品名称：</div>\n`;
	contents += `					<div class="g-c-51">安徽省电话费</div>\n`;
	contents += `				</div>\n`;
	contents += `				<div class="g-flex g-m-b-16">\n`;
	contents += `					<div class="g-c-333">商品名称：</div>\n`;
	contents += `					<div class="g-c-51">安徽省电话费</div>\n`;
	contents += `				</div>\n`;
	contents += `				<div class="g-flex g-m-b-16">\n`;
	contents += `					<div class="g-c-333">商品名称：</div>\n`;
	contents += `					<div class="g-c-51">安徽省电话费</div>\n`;
	contents += `				</div>\n`;
	contents += `				<div class="g-flex g-m-b-16">\n`;
	contents += `					<div class="g-c-333">商品名称：</div>\n`;
	contents += `					<div class="g-c-51">安徽省电话费</div>\n`;
	contents += `				</div>\n`;
	contents += `			</div>\n`;
	contents += `		</div>\n`;
	contents += `		<vc${m}-button @click="$router.back()">取消</vc${m}-button>\n`;
	contents += `		<vc${m}-button type="primary" @click="handleSubmit">确定</vc${m}-button>\n`;
	contents += `	</div>\n`;
	contents += `</template>\n`;
	contents += `\n`;
	contents += `<script>\n`;
	contents += `\n`;
	contents += `export default {\n`;
	contents += `	name: 'v-tpl-form',\n`;
	contents += `	components: {\n`;
	contents += `	},\n`;
	contents += `	data() {\n`;
	contents += `		return {\n`;
	contents += `			company: ['阿里', '有赞', '网易', '滴滴'],\n`;
	contents += `			index: 1,\n`;
	contents += `			setShow: false,\n`;
	contents += `			formValidate: {\n`;
	contents += `				product_name: 'xxxxx',\n`;
	contents += `				product_sn: '',\n`;
	contents += `				original_img: '',\n`;
	contents += `				weight: '',\n`;
	contents += `				items: [\n`;
	contents += `					{\n`;
	contents += `						index: 1,\n`;
	contents += `						date: '',\n`;
	contents += `						pay_type: [],\n`;
	contents += `						amount: null,\n`;
	contents += `						imgs: []\n`;
	contents += `					}\n`;
	contents += `				]\n`;
	contents += `			},\n`;
	contents += `			ruleValidate: {\n`;
	contents += `				product_name: [\n`;
	contents += `					{ \n`;
	contents += `						required: true, \n`;
	contents += `						message: '商品名称必须填写，最多100个字' \n`;
	contents += `					}\n`;
	contents += `				],\n`;
	contents += `				product_sn: [\n`;
	contents += `					{ \n`;
	contents += `						required: true,\n`;
	contents += `						message: '商品货号必须填写，且不能超过64个字符' \n`;
	contents += `					}\n`;
	contents += `				],\n`;
	contents += `				original_img: [\n`;
	contents += `					{ \n`;
	contents += `						required: true, \n`;
	contents += `						message: '最少添加一张商品图片' \n`;
	contents += `					}\n`;
	contents += `				],\n`;
	contents += `				contact: [\n`;
	contents += `					{ \n`;
	contents += `						required: true, \n`;
	contents += `						message: '商品价格为不能超过7个字符的正数，且不能超过小数点后两位' \n`;
	contents += `					}\n`;
	contents += `				],\n`;
	contents += `				weight: [\n`;
	contents += `					{ \n`;
	contents += `						required: true, \n`;
	contents += `						message: '商品重量为不能超过9个字符的正整数', \n`;
	contents += `						trigger: 'change' \n`;
	contents += `					}\n`;
	contents += `				],\n`;
	contents += `				\n`;
	contents += `			}\n`;
	contents += `		};\n`;
	contents += `	},\n`;
	contents += `	methods: {\n`;
	contents += `		handleAdd() {\n`;
	contents += `			this.index++;\n`;
	contents += `			this.formValidate.items.push({\n`;
	contents += `				index: this.index,\n`;
	contents += `				date: '',\n`;
	contents += `				pay_type: [],\n`;
	contents += `				amount: null\n`;
	contents += `			});\n`;
	contents += `		},\n`;
	contents += `		handleDel(index) {\n`;
	contents += `			this.formValidate.items = this.formValidate.items.filter((item) => {\n`;
	contents += `				return item.index !== index;\n`;
	contents += `			});\n`;
	contents += `		},\n`;
	contents += `		handleSubmit(name) {\n`;
	contents += `			this.$refs[name].validate().then((res) => {\n`;
	contents += `					// ..\n`;
	contents += `				}).catch((res) => {\n`;
	contents += `					console.log(res);\n`;
	contents += `				});\n`;
	contents += `		},\n`;
	contents += `		handleSet() {\n`;
	contents += `			this.setShow = !this.setShow;\n`;
	contents += `			return this.setShow;\n`;
	contents += `		},\n`;
	contents += `	},\n`;
	contents += `};\n`;
	contents += `</script>\n`;
	contents += `\n`;
	contents += `<style lang="scss">\n`;
	contents += `</style>\n`;



	return contents;
};
