export const component = (content, opts = {}) => {
	const { mutation, pathArr, project, obj } = opts;
	let contents = '';
	contents += `<template>\n`;
	contents += `	<i-form \n`;
	contents += `		ref="form" \n`;
	contents += `		:model="formValidate" \n`;
	contents += `		:rules="ruleValidate" \n`;
	contents += `		:label-width="120"\n`;
	contents += `		class="v-tpl-form"\n`;
	contents += `		style="width: 500px" \n`;
	contents += `		position="left"\n`;
	contents += `	>\n`;
	contents += `		<i-form-item label="客户公司名称:" prop="name">\n`;
	contents += `			<i-input v-model="formValidate.name" disabled placeholder="请输入客户公司名称" />\n`;
	contents += `		</i-form-item>\n`;
	contents += `		<i-form-item label="客户姓名:" prop="customer_name">\n`;
	contents += `			<i-input v-model="formValidate.customer_name" placeholder="请输入客户姓名" />\n`;
	contents += `		</i-form-item>\n`;
	contents += `		<i-form-item label="客户合同公司:" prop="contact">\n`;
	contents += `			<i-input v-model="formValidate.contact" placeholder="请填写合同签订公司" />\n`;
	contents += `		</i-form-item>\n`;
	contents += `		<i-form-item label="我方合同公司:" prop="my_company">\n`;
	contents += `			<i-select \n`;
	contents += `				v-model="formValidate.my_company"\n`;
	contents += `				clearable \n`;
	contents += `				placeholder="请选择我方合同公司"\n`;
	contents += `			>\n`;
	contents += `				<i-option \n`;
	contents += `					v-for="(item, index) in company" \n`;
	contents += `					:key="index" \n`;
	contents += `					value="item"\n`;
	contents += `				>\n`;
	contents += `					{{ item }}\n`;
	contents += `				</i-option>\n`;
	contents += `			</i-select>\n`;
	contents += `			<span class="_right">添加</span>\n`;
	contents += `		</i-form-item>\n`;
	contents += `		<i-form-item label="成交时间" prop="deal_time">\n`;
	contents += `			<i-date-picker \n`;
	contents += `				v-model="formValidate.deal_time" \n`;
	contents += `				style="width: 100%"\n`;
	contents += `				type="datetime" \n`;
	contents += `				placeholder="请选择成交时间"\n`;
	contents += `			/>\n`;
	contents += `		</i-form-item>\n`;
	contents += `		<i-form-item label="客户手机号" prop="mobile">\n`;
	contents += `			<i-input \n`;
	contents += `				v-model="formValidate.mobile" \n`;
	contents += `				:maxlength="11"\n`;
	contents += `				placeholder="请输入客户手机号"\n`;
	contents += `			/>\n`;
	contents += `		</i-form-item>\n`;
	contents += `		<i-form-item label="不分单认证" prop="permit">\n`;
	contents += `			<i-input \n`;
	contents += `				v-model="formValidate.permit" \n`;
	contents += `				placeholder="请输入认证验证码"\n`;
	contents += `			/>\n`;
	contents += `		</i-form-item>\n`;
	contents += `		<i-form-item label="合同金额" prop="amount">\n`;
	contents += `			<i-input-number\n`;
	contents += `				v-model="formValidate.amount" \n`;
	contents += `				:min="0"\n`;
	contents += `				:precision="2"\n`;
	contents += `				style="width: 100%"\n`;
	contents += `				placeholder="请输入合同金额"\n`;
	contents += `			/>\n`;
	contents += `		</i-form-item>\n`;
	contents += `		<i-form-item \n`;
	contents += `			v-for="(item, index) in formValidate.items"\n`;
	contents += `			:key="item.index"\n`;
	contents += `			\n`;
	contents += `			:label="index === 0 ? '缴款方式' : ''"\n`;
	contents += `		>\n`;
	contents += `			<i-form-item\n`;
	contents += `				:prop="'items.' + index + '.date'" \n`;
	contents += `				:rules="{required: true, message: '请选择成交时间'}"\n`;
	contents += `			>\n`;
	contents += `				<i-date-picker \n`;
	contents += `					v-model="item.date" \n`;
	contents += `					style="width: 100%" \n`;
	contents += `					type="datetime"\n`;
	contents += `					placeholder="请选择成交时间" \n`;
	contents += `				/>\n`;
	contents += `			</i-form-item>\n`;
	contents += `			<i-form-item \n`;
	contents += `				:prop="'items.' + index + '.pay_type'" \n`;
	contents += `				:rules="{required: true, message: '选择付款方式'}"\n`;
	contents += `			>\n`;
	contents += `				<i-cascader \n`;
	contents += `					:data="payType" \n`;
	contents += `					v-model="item.pay_type" \n`;
	contents += `					class="g-m-t-24"\n`;
	contents += `					placeholder="选择付款方式"\n`;
	contents += `				/>\n`;
	contents += `			</i-form-item>\n`;
	contents += `			<i-form-item \n`;
	contents += `				:prop="'items.' + index + '.amount'" \n`;
	contents += `				:rules="{required: true, message: '请输入付款金额'}"\n`;
	contents += `			>\n`;
	contents += `				<i-input-number\n`;
	contents += `					v-model="item.amount" \n`;
	contents += `					:min="0"\n`;
	contents += `					:precision="2"\n`;
	contents += `					style="width: 100%; margin-top: 20px"\n`;
	contents += `					placeholder="请输入付款金额"\n`;
	contents += `				/>\n`;
	contents += `			</i-form-item>\n`;
	contents += `			<i-form-item\n`;
	contents += `				:prop="'items.' + index + '.imgs'" \n`;
	contents += `				:rules="{required: true, message: '请选择图片'}"\n`;
	contents += `			>\n`;
	contents += `				<vc-imgs-picker v-model="item.imgs" class="g-m-t-24" />\n`;
	contents += `			</i-form-item>\n`;
	contents += `			\n`;
	contents += `			<span\n`;
	contents += `				class="_del" \n`;
	contents += `				@click="handleDel(item.index)"\n`;
	contents += `			>\n`;
	contents += `				删除\n`;
	contents += `			</span>\n`;
	contents += `		</i-form-item>\n`;
	contents += `		<div class="g-flex-ac">\n`;
	contents += `			<div style="width: 120px"/>\n`;
	contents += `			<div class="btn" @click="handleAdd">Add Item</div>\n`;
	contents += `		</div>\n`;
	contents += `		<div class="g-flex-ac">\n`;
	contents += `			<div style="width: 120px"/>\n`;
	contents += `			<div class="btn g-m-t-20" @click="handleSubmit">提交</div>\n`;
	contents += `		</div>\n`;
	contents += `	</i-form>\n`;
	contents += `</template>\n`;
	contents += `\n`;
	contents += `<script>\n`;
	contents += `import * as types from '@mutations/${mutation}';\n`;
	contents += `import { \n`;
	contents += `	Form, FormItem, Input, InputNumber, \n`;
	contents += `	Select, Option, DatePicker, Cascader, Message\n`;
	contents += `} from 'iview';\n`;
	contents += `// utils\n`;
	contents += `import { dataValidity } from '@utils/utils';\n`;
	contents += `import { ImgsPicker } from 'wya-vc';\n`;
	contents += `\n`;
	contents += `const data = [\n`;
	contents += `	{\n`;
	contents += `		value: 'beijing',\n`;
	contents += `		label: '北京',\n`;
	contents += `		children: [\n`;
	contents += `			{\n`;
	contents += `				value: 'gugong',\n`;
	contents += `				label: '故宫'\n`;
	contents += `			},\n`;
	contents += `			{\n`;
	contents += `				value: 'tiantan',\n`;
	contents += `				label: '天坛'\n`;
	contents += `			},\n`;
	contents += `			{\n`;
	contents += `				value: 'wangfujing',\n`;
	contents += `				label: '王府井'\n`;
	contents += `			}\n`;
	contents += `		]\n`;
	contents += `	}, \n`;
	contents += `	{\n`;
	contents += `		value: 'jiangsu',\n`;
	contents += `		label: '江苏',\n`;
	contents += `		children: [\n`;
	contents += `			{\n`;
	contents += `				value: 'nanjing',\n`;
	contents += `				label: '南京',\n`;
	contents += `				children: [\n`;
	contents += `					{\n`;
	contents += `						value: 'fuzimiao',\n`;
	contents += `						label: '夫子庙',\n`;
	contents += `					}\n`;
	contents += `				]\n`;
	contents += `			},\n`;
	contents += `			{\n`;
	contents += `				value: 'suzhou',\n`;
	contents += `				label: '苏州',\n`;
	contents += `				children: [\n`;
	contents += `					{\n`;
	contents += `						value: 'zhuozhengyuan',\n`;
	contents += `						label: '拙政园',\n`;
	contents += `					},\n`;
	contents += `					{\n`;
	contents += `						value: 'shizilin',\n`;
	contents += `						label: '狮子林',\n`;
	contents += `					}\n`;
	contents += `				]\n`;
	contents += `			}\n`;
	contents += `		],\n`;
	contents += `	}];\n`;
	contents += `\n`;
	contents += `export default {\n`;
	contents += `	name: '${project}-content',\n`;
	contents += `	components: {\n`;
	contents += `		'i-form': Form,\n`;
	contents += `		'i-form-item': FormItem,\n`;
	contents += `		'i-input': Input,\n`;
	contents += `		'i-input-number': InputNumber,\n`;
	contents += `		'i-select': Select,\n`;
	contents += `		'i-option': Option,\n`;
	contents += `		'i-date-picker': DatePicker,\n`;
	contents += `		'i-cascader': Cascader,\n`;
	contents += `		'vc-imgs-picker': ImgsPicker\n`;
	contents += `	},\n`;
	contents += `	data() {\n`;
	contents += `		return {\n`;
	contents += `			company: ['阿里', '有赞', '网易', '滴滴'],\n`;
	contents += `			payType: data,\n`;
	contents += `			index: 1,\n`;
	contents += `			formValidate: {\n`;
	contents += `				name: 'xxxxx',\n`;
	contents += `				customer_name: '',\n`;
	contents += `				contact: '',\n`;
	contents += `				my_company: '',\n`;
	contents += `				deal_time: '',\n`;
	contents += `				mobile: '',\n`;
	contents += `				permit: '',\n`;
	contents += `				amount: null,\n`;
	contents += `				items: [\n`;
	contents += `					{\n`;
	contents += `						index: 1,\n`;
	contents += `						date: '',\n`;
	contents += `						pay_type: [],\n`;
	contents += `						amount: null,\n`;
	contents += `						imgs: []\n`;
	contents += `					}\n`;
	contents += `				]\n`;
	contents += `			},\n`;
	contents += `			ruleValidate: {\n`;
	contents += `				name: [\n`;
	contents += `					{ required: true, message: '请输入客户公司名称' }\n`;
	contents += `				],\n`;
	contents += `				customer_name: [\n`;
	contents += `					{ required: true, message: '请输入客户姓名' }\n`;
	contents += `				],\n`;
	contents += `				contact: [\n`;
	contents += `					{ required: true, message: '请填写合同签订公司' }\n`;
	contents += `				],\n`;
	contents += `				my_company: [\n`;
	contents += `					{ required: true, message: '请选择我方合同公司', trigger: 'change' }\n`;
	contents += `				],\n`;
	contents += `				deal_time: [\n`;
	contents += `					{ required: true, type: "date", message: '请选择成交时间', trigger: 'change' }\n`;
	contents += `				],\n`;
	contents += `				mobile: [\n`;
	contents += `					{ required: true, message: '请输入客户手机号', trigger: 'blur' }, \n`;
	contents += `					{ type: 'validMobile', message: '手机号格式不正确', validator: dataValidity }\n`;
	contents += `				],\n`;
	contents += `				permit: [\n`;
	contents += `					{ required: true, message: '请输入认证验证码' }\n`;
	contents += `				],\n`;
	contents += `				amount: [\n`;
	contents += `					{ required: true, type: 'number', message: '请输入合同金额' }\n`;
	contents += `				]\n`;
	contents += `			}\n`;
	contents += `		};\n`;
	contents += `	},\n`;
	contents += `	mounted() {\n`;
	contents += `	},\n`;
	contents += `	methods: {\n`;
	contents += `		handleAdd() {\n`;
	contents += `			this.index++;\n`;
	contents += `			this.formValidate.items.push({\n`;
	contents += `				index: this.index,\n`;
	contents += `				date: '',\n`;
	contents += `				pay_type: [],\n`;
	contents += `				amount: null\n`;
	contents += `			});\n`;
	contents += `		},\n`;
	contents += `		handleDel(index) {\n`;
	contents += `			this.formValidate.items = this.formValidate.items.filter((item) => {\n`;
	contents += `				return item.index !== index;\n`;
	contents += `			});\n`;
	contents += `		},\n`;
	contents += `		handleSubmit(name) {\n`;
	contents += `			this.$refs.form.validate((isValid) => {\n`;
	contents += `				if (isValid) {\n`;
	contents += `					Message.success('Success!');\n`;
	contents += `				} else {\n`;
	contents += `					Message.error('Fail!');\n`;
	contents += `				}\n`;
	contents += `			});\n`;
	contents += `		},\n`;
	contents += `	},\n`;
	contents += `};\n`;
	contents += `</script>\n`;
	contents += `\n`;
	contents += `<style lang="scss" scoped>\n`;
	contents += `.v-tpl-form {\n`;
	contents += `	.btn {\n`;
	contents += `		color: #0085ff;\n`;
	contents += `		cursor: pointer;\n`;
	contents += `	}\n`;
	contents += `	._right {\n`;
	contents += `		@extend .btn;\n`;
	contents += `		position: absolute; \n`;
	contents += `		right: -30px; \n`;
	contents += `		top: 0;\n`;
	contents += `	}\n`;
	contents += `	._del {\n`;
	contents += `		@extend .btn;\n`;
	contents += `		display: block;\n`;
	contents += `		margin-top: 24px;\n`;
	contents += `	}\n`;
	contents += `}\n`;
	contents += `</style>\n`;

	return contents;
};
