export const container = (content, opts = {}) => {
	const { mutation, pathArr, project, obj, title } = opts;
	let contents = '';
	contents += `<template>\n`;
	contents += `	<set-title title="${title}" style="padding: 20px">\n`;
	contents += `		<${project}-content />\n`;
	contents += `	</set-title>\n`;
	contents += `</template>\n`;
	contents += `\n`;
	contents += `<script>\n`;
	contents += `import Content from '@components/${mutation}/${pathArr.slice(1).join("-")}/content';\n`;
	contents += `\n`;
	contents += `export default {\n`;
	contents += `	name: '${project}-${pathArr.join("-")}',\n`;
	contents += `	components: {\n`;
	contents += `		"${project}-content": Content,\n`;
	contents += `	},\n`;
	contents += `	data() {\n`;
	contents += `		return {\n`;
	contents += `		};\n`;
	contents += `	},\n`;
	contents += `	created() {\n`;
	contents += `	},\n`;
	contents += `	methods: {\n`;
	contents += `	},\n`;
	contents += `};\n`;
	contents += `</script>\n`;
	contents += `\n`;
	contents += `<style lang="scss" scoped>\n`;
	contents += `</style>\n`;
	return contents;
};
