import { getNewContent } from '../utils/helper';

export const filter = (content, opts = {}) => {
	const { mutation, pathArr, project, obj, pagingMode: mode } = opts;
	let extra = pathArr.slice(1).map(item => `${item[0].toUpperCase()}${item.slice(1)}`).join('');

	let mutationType = `${pathArr.join('_').toUpperCase()}`;
	let pagingType = mutationType;

	if (pathArr.includes('list') === false) {
		pagingType = mutationType + '_LIST';
	}

	try {
		let contents = '';
		contents += `<template>\n`;
		contents += `	<div>\n`;
		contents += `		<vc-button \n`;
		contents += `			type="primary"\n`;
		contents += `			class="g-m-b-16"\n`;
		contents += `			@click="handleExport"\n`;
		contents += `		>\n`;
		contents += `			导出\n`;
		contents += `		</vc-button>\n`;
		contents += `		<div>\n`;
		contents += `			<span>退款信息：</span>\n`;
		contents += `			<vc-input\n`;
		contents += `				v-model="keywords.search" \n`;
		contents += `				placeholder="请输入关键字搜索" \n`;
		contents += `				style="width: 240px" \n`;
		contents += `				clearable\n`;
		contents += `				@enter="handleSearch"\n`;
		contents += `				@change="handleInputChange"\n`;
		contents += `			/>\n`;
		contents += `			<vc-button \n`;
		contents += `				type="primary"\n`;
		contents += `				class="g-m-l-24"\n`;
		contents += `				@click="handleSearch"\n`;
		contents += `			>\n`;
		contents += `				搜索\n`;
		contents += `			</vc-button>\n`;
		contents += `			<span\n`;
		contents += `				class="g-m-l-12 g-c-black-dark g-fs-12 g-pointer g-no-select"\n`;
		contents += `				@click="handleToggle"\n`;
		contents += `			>\n`;
		contents += `				{{ show ? '收起' : '展开' }}\n`;
		contents += `				<vc-icon :type="show ? 'triangle-up' : 'triangle-down'" class="g-fs-12" />\n`;
		contents += `			</span>\n`;
		contents += `		</div>\n`;
		contents += `		<vc-expand v-model="show">\n`;
		contents += `			<div class="g-pd-t-16">\n`;
		contents += `				<div\n`;
		contents += `					class="g-search-form g-lh-50 g-bg-f4"\n`;
		contents += `					style="padding-top: 5px; padding-bottom: 5px"\n`;
		contents += `				>\n`;
		contents += `					<div class="g-flex g-fw-w" style="min-width: 796px">\n`;
		contents += `						<div>\n`;
		contents += `							<span class="g-c-333 g-w-100">退款方式：</span>\n`;
		contents += `							<vc-input\n`;
		contents += `								v-model="keywords.name" \n`;
		contents += `								style="width: 160px" \n`;
		contents += `								placeholder="请输入公司名称" \n`;
		contents += `								@enter="handleSearch"\n`;
		contents += `								@change="handleInputChange"\n`;
		contents += `							/>\n`;
		contents += `						</div>\n`;
		contents += `						<div>\n`;
		contents += `							<span class="g-c-333 g-w-100">退款传方式：</span>\n`;
		contents += `							<vc-input\n`;
		contents += `								v-model="keywords.name" \n`;
		contents += `								style="width: 220px" \n`;
		contents += `								placeholder="请输入公司名称" \n`;
		contents += `								@enter="handleSearch"\n`;
		contents += `								@change="handleInputChange"\n`;
		contents += `							/>\n`;
		contents += `						</div>\n`;
		contents += `					</div>\n`;
		contents += `				</div>\n`;
		contents += `			</div>\n`;
		contents += `		</vc-expand>\n`;
		contents += `	</div>\n`;
		contents += `</template>\n`;
		contents += `\n`;
		contents += `<script>\n`;
		contents += `import { URL } from '@utils/utils';\n`;
		contents += `import { debounce } from 'lodash';\n`;
		contents += `\n`;
		contents += `export default {\n`;
		contents += `	name: '${project}-filter',\n`;
		contents += `	components: {\n`;
		contents += `	},\n`;
		contents += `	data() {\n`;
		contents += `		const { query = {} } = this.$route;\n`;
		contents += `		return {\n`;
		contents += `			keywords: {\n`;
		contents += `				search: String(query.search || ''),\n`;
		contents += `				name: String(query.name || ''),\n`;
		contents += `			},\n`;
		contents += `			show: false,\n`;
		contents += `		};\n`;
		contents += `	},\n`;
		contents += `	methods: {\n`;
		contents += `		handleSearch: debounce(function (value) {\n`;
		contents += `			let query = {\n`;
		contents += `				...this.$route.query,\n`;
		contents += `				...this.keywords,\n`;
		contents += `			};\n`;
		contents += `			this.$router.replace(URL.merge({\n`;
		contents += `				path: '/${pathArr.join('/')}', \n`;
		contents += `				query\n`;
		contents += `			}));\n`;
		contents += `			this.$store.commit('${pagingType}_INIT');\n`;
		contents += `		}, 300),\n`;
		contents += `		handleToggle() {\n`;
		contents += `			this.show = !this.show;\n`;
		contents += `		},\n`;
		contents += `		handleChange(obj) {\n`;
		contents += `			let type = Object.keys(obj)[0];\n`;
		contents += `			let value = obj[type];\n`;
		contents += `			this.keywords[type] = value;\n`;
		contents += `			this.handleSearch();\n`;
		contents += `		},\n`;
		contents += `		handleInputChange(e) {\n`;
		contents += `			if (!e.target.value) {\n`;
		contents += `				this.handleSearch();\n`;
		contents += `			}\n`;
		contents += `		},\n`;
		contents += `		handleExport() {}\n`;
		contents += `	}\n`;
		contents += `};\n`;
		contents += `\n`;
		contents += `</script>\n`;
		contents += `\n`;
		contents += `<style lang="scss">\n`;
		contents += `\n`;
		contents += `</style>\n`;

		return contents;
	} catch (e) {
		console.log(e);
		return content;
	}
};

