export const router = (opts = {}) => {
	const { name, action, pathArr, componentArr, obj } = opts;
	let contents = '';
	contents += `import { redirectUserToLogin, redirectUserToHome } from '@routers/auth';\n`;
	contents += `export const ${action}Config = [\n`;
	contents += `	{\n`;
	contents += `		path: '/${action}',\n`;
	contents += `		childRoutes: [\n`;
	contents += `			{\n`;
	contents += `				path: '${pathArr.slice(1).join('/')}',\n`;
	contents += `				getComponent: (nextState, cb) => {\n`;
	contents += `					require.ensure([], (require) => {\n`;
	contents += `						cb(null, require('./Modules/${name}').default);\n`;
	contents += `					});\n`;
	contents += `				},\n`;
	contents += `				onEnter: redirectUserToLogin\n`;
	contents += `			},\n`;
	contents += `		]\n`;
	contents += `	},\n`;
	contents += `];\n`;
	return contents;
};
